### ISSUE TITLE
Update mysql recorder, simplify mysql group_recorder

### ISSUE THREAD

**Issue by blthayer** [gridlab-d/gridlab-d#1095]
Initial Checklist prior to submitting the issue. Check the bellow boxes to the best of your knowledge:

- [x] I have not found an open issue describing the same problem.
- [x] I went through "CONTRIBUTING.MD" before deciding to submit the issue.
- [x] While building GridLAB-D, I followed all steps as detailed in GridLAB-D Wiki.

------------------------------------------------------------------------------------------------------------
This issue has two tasks that are closely related:

## Task 1: Update mysql recorder to use the new, efficient query engine built by @eberleim.

- Rather than sending an update to MySQL for every time step, use Mark's query engine to build up longer queries and commit them when the 'query buffer' is full
- Update documentation to reflect change (new inputs for maximum query length, etc.)
- Make recorders capable of taking in 'group', but maintain group_recorder for consistency with the tape module.
- Add 'complex_part' object property (or should it be property.complex_part notation?)
-- Columns for property value recording would be in format propName_complex_part

## Task 2: Simplify mysql group_recorder
At time of writing, mysql module group_recorder pull request is open [here](https://github.com/gridlab-d/gridlab-d/pull/1093).

The initial creation of the mysql group_recorder was done under the idea of 'replicate the functionality found in tape's group_recorder.' However, this is not the best implementation for working with databases. Specifically, we create a _lot_ of columns. Instead, group_recorder tables should be nearly identical to the regular recorder tables. Specifically:
- Column for id
- Column for timestamp
- Column for object name
- Column for each complex part of a property (in format propName_complex_part
-- Should we remove the 'complex_part' property and instead use the property.complex_part notation?

-------------------------------------------------------------------------------------------------------------

**Comment by blthayer** [comment]
The final bullet of task 1 and task 2 are closely linked to: https://github.com/gridlab-d/gridlab-d/issues/1063

@eberleim
